name: Changelog & Table of contents

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  changelog-mtoc:
    name: Generate CHANGELOG and table of contents
    runs-on: ubuntu-latest
    steps:
      - name: Install git cliff & mtoc
        run: |
          rustup default stable
          cargo install git-cliff
          cargo install mtoc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update CHANGELOG.md in main branch
        run: |
          git checkout main
          git pull origin main
          git config --global user.name 'containerscrew'
          git config --global user.email 'containerscrew@users.noreply.github.com'
          make generate-changelog
          make mtoc
          git add --all
          git commit -m "Update CHANGELOG.md & table of contents"
          git push origin main
